apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"
  url: 'https://argocd.aaronschweig.dev'
  resource.customizations.health.networking.k8s.io_Ingress: |
    hs = {}
    hs.status = "Healthy"
    return hs
  resource.compareoptions: |
    ignoreAggregatedRoles: true
  dex.config: |
    staticClients:
    - id: vault-oidc
      secret: $dex.github.clientSecret
      name: 'Vault OIDC'
      redirectURIs:
        - https://vault.aaronschweig.dev/ui/vault/auth/oidc/oidc/callback # login via UI
        - http://localhost:8250/oidc/callback # login via cli
    - id: ams-pro-k8s
      public: true
      name: 'AMS-Pro Cluster'
      redirectURIs:
        - http://localhost:8000
        
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: f41a4aa0aebc2f0ea394
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: ams-pro
          teams:
          - devops
          - infrastructure