apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      automountServiceAccountToken: true
      serviceAccountName: argocd-server
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: custom-tools
              subPath: argocd-vault-plugin
              mountPath: /usr/local/bin/argocd-vault-plugin
          env:
            - name: AVP_TYPE
              value: vault
            - name: VAULT_ADDR
              value: http://vault.default.svc.cluster.local:8200
            - name: AVP_AUTH_TYPE
              value: k8s
            - name: AVP_K8S_ROLE
              value: argocd
              
        # argocd-vault-plugin with Helm
        - name: avp-helm
          command: [/var/run/argocd/argocd-cmp-server]
          image: quay.io/argoproj/argocd:v2.7.4
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: tmp

            # Register plugins into sidecar
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: avp-helm.yaml
              name: cmp-plugin

            # Important: Mount tools into $PATH
            - name: custom-tools
              subPath: argocd-vault-plugin
              mountPath: /usr/local/bin/argocd-vault-plugin

        # argocd-vault-plugin with Kustomize
        - name: avp-kustomize
          command: [/var/run/argocd/argocd-cmp-server]
          image: quay.io/argoproj/argocd:v2.7.4
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: tmp

            # Register plugins into sidecar
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: avp-kustomize.yaml
              name: cmp-plugin

            # Important: Mount tools into $PATH
            - name: custom-tools
              subPath: argocd-vault-plugin
              mountPath: /usr/local/bin/argocd-vault-plugin

        # argocd-vault-plugin with plain YAML
        - name: avp
          command: [/var/run/argocd/argocd-cmp-server]
          image: quay.io/argoproj/argocd:v2.7.4
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: tmp

            # Register plugins into sidecar
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: avp.yaml
              name: cmp-plugin

            # Important: Mount tools into $PATH
            - name: custom-tools
              subPath: argocd-vault-plugin
              mountPath: /usr/local/bin/argocd-vault-plugin

      volumes:
        - name: custom-tools
          emptyDir: {}
        - configMap:
            name: cmp-plugin
          name: cmp-plugin
      initContainers:
        - name: download-tools
          image: alpine:3.15
          command: [sh, -c]
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
          args:
            - |
              set -x
              RAW_VERSION=${AVP_VERSION#v};
              wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/${AVP_VERSION}/argocd-vault-plugin_${RAW_VERSION}_linux_amd64;
              chmod +x argocd-vault-plugin;
              mv argocd-vault-plugin /custom-tools/;
          env:
            - name: AVP_VERSION
              # renovate: https://github.com/argoproj-labs/argocd-vault-plugin/releases
              value: v1.16.1
