apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-sdb
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/aaronschweig/auto-sdb'
    path: "kubernetes"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true