apiVersion: v1
kind: Secret
metadata:
  name: ghr-registry
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: "secret/data/github"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: <ghcr-dockerconfig>
