apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    avp.kubernetes.io/path: "secret/data/gcp"
spec:
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: gcp-credentials
      namespace: crossplane-system
  projectID: <project-id>
---
# GCP Admin service account secret - used by GCP ProviderConfig
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: crossplane-system
  annotations:
    avp.kubernetes.io/path: "secret/data/gcp"
stringData:
  credentials: <sa-gcp.json>
