apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: aws-credentials
      namespace: crossplane-system
      key: creds
---
# AWS Access Key Credentials
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crossplane-system
  annotations:
    avp.kubernetes.io/path: "secret/data/aws"
stringData:
  creds: |
    aws_access_key_id: <accessKeyIDFull>
    aws_secret_access_key: <accessKeySecretFull>
