apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/prod
    plugin:
      name: argocd-vault-plugin-kustomize
    repoURL: https://github.com/aaronschweig/infrastructure
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true