apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # renovate:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.2/manifests/install.yaml
  - overlays/ingress.yaml
  - overlays/repo-creds.yaml

patchesStrategicMerge:
  - overlays/argocd-cm.yaml
  - overlays/argocd-rbac-cm.yaml
  - overlays/argocd-secret.yaml
  - overlays/repo-server-deploy.yaml
  - overlays/argocd-notifications-cm.yaml
  - overlays/argocd-notifications-secret.yaml


patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server
  path: overlays/server-extra-args.yaml
