apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# renovate:
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.4/manifests/install.yaml
- overlays/ingress.yaml
- overlays/repo-creds.yaml
- overlays/cmp-plugin.yaml

patches:
- path: overlays/argocd-cm.yaml
- path: overlays/argocd-rbac-cm.yaml
- path: overlays/argocd-secret.yaml
- path: overlays/repo-server-deploy.yaml
- path: overlays/argocd-notifications-cm.yaml
- path: overlays/argocd-notifications-secret.yaml
- path: overlays/argocd-cmd-cm.yaml
