apiVersionOverrides:
  ingress: networking.k8s.io/v1

server:
  ingress:
    enabled: true
    hosts:
      - argocd.aaronschweig.dev
    tls:
      - hosts:
        - argocd.aaronschweig.dev
        secretName: argocd-aaronschweig-dev
  extraArgs:
    - '--insecure'
  config:
    admin.enabled: "false"
    url: 'https://argocd.aaronschweig.dev'
    resource.customizations.health.networking.k8s.io_Ingress: |
      hs = {}
      hs.status = "Healthy"
      return hs
    dex.config: |
      staticClients:
      - id: vault-oidc
        secret: $dex.github.clientSecret
        name: 'Vault OIDC'
        redirectURIs:
          - https://vault.aaronschweig.dev/ui/vault/auth/oidc/oidc/callback # login via UI
          - http://localhost:8250/oidc/callback # login via cli
          
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: f41a4aa0aebc2f0ea394
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: ams-pro
    configManagementPlugins: |
      - name: argocd-vault
        generate:
          command: [argocd-vault-plugin]
          args: 
            - generate
            - ./
      - name: argocd-vault-plugin-kustomize
        generate:
          command: ["sh", "-c"]
          args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
  rbacConfig:
    policy.csv: |
      g, ams-pro:devops, role:admin
    policy.default: role:readonly

repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
  initContainers:
  - name: download-tools
    image: registry.access.redhat.com/ubi8
    command: [sh, -c]
    args:
      - curl -L https://github.com/IBM/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin && 
        chmod +x argocd-vault-plugin && 
        mv argocd-vault-plugin /custom-tools/
    env:
      - name: AVP_VERSION
        value: 1.9.0
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - name: custom-tools
    subPath: argocd-vault-plugin
    mountPath: /usr/local/bin/argocd-vault-plugin
  env:
  - name: AVP_TYPE
    value: vault
  - name: VAULT_ADDR
    value: http://vault.default.svc.cluster.local:8200
  - name: AVP_AUTH_TYPE
    value: k8s
  - name: AVP_K8S_ROLE
    value: argocd

configs:
  credentialTemplates:
    https-creds:
      url: https://github.com/ams-pro
      username: aaronschweig
      password: <PAT>
  secret:
    extra:
      dex.github.clientSecret: <CLIENT_SECRET>