apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.19.0
    helm:
      releaseName: vault
      values: |
        injector:
          enabled: false
        server:
          dev:
            enabled: false 
          image:
            tag: "1.9.3"
          ingress:
            enabled: true
            hosts:
              - host: vault.aaronschweig.dev
            tls:
              - hosts:
                - vault.aaronschweig.dev
                secretName: wildcard-aaronschweig-dev
          dataStorage:
            size: 1Gi
