apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.19.0
    helm:
      releaseName: vault
      values: |
        injector:
          enabled: false
        server:
          dev:
            enabled: false 
          ingress:
            enabled: true
            hosts:
              - host: vault.aaronschweig.dev
            tls:
              - hosts:
                - vault.aaronschweig.dev
                secretName: wildcard-aaronschweig-dev
          dataStorage:
            size: 1Gi
          # postStart:
          #   - /bin/sh
          #   - -c
          #   - |
          #     sleep 10s &&\
          #     printf 'path "secret/*"{\ncapabilities=["read"]\n}' | vault policy write argocd-policy - &&\
          #     vault auth enable kubernetes &&\
          #     vault write auth/kubernetes/config\
          #       kubernetes_host=https://kubernetes.default.svc:443 \
          #       disable_iss_validation=true &&\
          #     vault write auth/kubernetes/role/argocd \
          #       bound_service_account_names=default \
          #       bound_service_account_namespaces=* \
          #       policies="avp-read-policy"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true