apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: aaron.schweig@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: aaron.schweig@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key